import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans, MonteCarlo } from "next/font/google";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
  // weight: ["300", "400", "500", "600", "700", "900"],
});
const monteCarlo = MonteCarlo({
  subsets: ["latin"],
  variable: "--font-monte-carlo",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(dmSans);
  return (
    <html lang="en">
      <body className={`${dmSans.variable} ${monteCarlo.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
